/* dialogue.js — citation-bound questions to the corpus.

   Retrieval happens here, in the browser, against the copy the reader opened.
   Only the passages it selects are sent onward, never the corpus. */
import * as C from "./corpus.js";
import { esc, nf, citeChip } from "./app.js";

const el = h => { const t = document.createElement("template"); t.innerHTML = h.trim(); return t.content.firstElementChild; };

const MODES = [
  ["scholarly", "Source-critical", "Marks the limits of what the passages establish."],
  ["prosopographic", "Prosopographic", "Organises the answer around the people the passages name."],
  ["critical", "Critical", "Separates what the passages license from what they are taken to license."],
];

const verlauf = [];

export function renderDialogue(view) {
  view.append(el(`<div>
    <div class="viewhead"><span class="tag">Dialogue</span>
      <h1>Put a question to the corpus</h1>
      <p class="lede">Retrieval runs in your browser and selects passages from the files you opened. Only
      those passages and your question are sent onward; the answer must cite them, and may assert nothing
      beyond them.</p></div>

    <div class="panel" id="dpanel">
      <div class="toolbar">
        <select id="dmode">${MODES.map(([v, l]) => `<option value="${v}">${l}</option>`).join("")}</select>
        <span class="fine" id="dmodehint">${MODES[0][2]}</span>
      </div>
      <textarea id="dq" rows="3" placeholder="e.g. What does the book claim about wartime work on uranium enrichment, and on what evidence?"></textarea>
      <div class="btnrow">
        <button class="primary" id="dsend">Ask</button>
        <span class="fine" id="dstate"></span>
      </div>
    </div>

    <div id="dout"></div>
  </div>`));

  const q = view.querySelector("#dq"), out = view.querySelector("#dout");
  const state = view.querySelector("#dstate"), btn = view.querySelector("#dsend");
  const mode = view.querySelector("#dmode"), hint = view.querySelector("#dmodehint");
  mode.onchange = () => { hint.textContent = (MODES.find(m => m[0] === mode.value) || MODES[0])[2]; };

  if (!C.isOpen()) {
    view.querySelector("#dpanel").before(el(`<div class="locked">
      <strong>The evidence mode needs your own copies</strong>
      <p style="margin:.3rem 0 .9rem;font-size:.9rem">Without it there are no passages to bind an answer to,
      and an unbound answer about this material is exactly what this apparatus exists to avoid. Open them from the button in the top right — the book is a free download.</p></div>`));
    btn.disabled = true;
    return;
  }

  btn.onclick = async () => {
    const frage = q.value.trim();
    if (frage.length < 5) { state.textContent = "Please formulate a question."; return; }
    btn.disabled = true; state.textContent = "Retrieving passages …";

    const treffer = C.retrieve(frage, 12);
    if (!treffer.length) {
      state.textContent = "";
      out.prepend(el(`<div class="statebox warn">No passage in your copy matches closely enough. Try other
        wording, or a term the corpus actually uses.</div>`));
      btn.disabled = false; return;
    }

    const passagen = treffer.map(t => ({
      zitat: t.cite ? t.cite.label : "unlocated",
      werk: t.cite ? t.cite.titel : "",
      text: t.text,
    }));
    verlauf.push({ rolle: "user", text: frage });
    state.textContent = `Asking with ${passagen.length} passages …`;

    let data;
    try {
      const r = await fetch("/.netlify/functions/dialogue", {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ frage, modus: mode.value, passagen, verlauf }),
      });
      data = await r.json();
    } catch (e) {
      data = { error: String(e && e.message ? e.message : e) };
    }
    state.textContent = ""; btn.disabled = false;

    if (data.error) {
      out.prepend(el(`<div class="statebox warn">${esc(data.error)}</div>`));
      verlauf.pop();
      return;
    }
    verlauf.push({ rolle: "assistant", text: data.antwort });

    out.prepend(el(`<div class="panel answer">
      <h2>${esc(frage)}</h2>
      <div class="readable">${data.antwort.split(/\n{2,}/).map(p => `<p>${esc(p)}</p>`).join("")}</div>
      <details class="evidence"><summary>${treffer.length} passages this answer was bound to</summary>
        <ul>${treffer.map(t => `<li>${citeChip(t.cite)}
          <span class="fine">score ${t.score}</span>
          <p class="readable" style="font-size:.9rem">${esc(t.text.slice(0, 420))}${t.text.length > 420 ? "…" : ""}</p>
        </li>`).join("")}</ul>
      </details>
      <p class="fine">Generated by a language model bound to the passages above. It can still be wrong —
      check each citation before you use it.</p>
    </div>`));
    q.value = "";
  };
}
